# Site settings
title: Ian Renyard
email: ian@renyard.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.renyard.co.uk" # the base hostname & protocol for your site
twitter_username: renyard
github_username:  renyard

timezone: Europe/London

# Build settings
markdown: kramdown
